if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(gcc_version "8.3.0")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS gcc_version)
        message(FATAL_ERROR "GCC version must be at least ${gcc_version}!")
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(clang_version "8.0.0")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS clang_version)
        message(FATAL_ERROR "Clang version must be at least ${clang_version}!")
    endif()
else()
    message(FATAL_ERROR "Unsupported compiler - ${CMAKE_CXX_COMPILER_ID}")
endif()

find_package(Boost 1.54 REQUIRED COMPONENTS program_options)

if(NOT Boost_FOUND)
    message(FATAL_ERROR "There is no required boost lib on system")
endif()
